# Azure ML Configuration for DR-PETS Training
# This file contains settings for deploying and running DR-PETS in Azure ML

azure:
  # Workspace settings
  subscription_id: null  # Set via environment variable AZURE_SUBSCRIPTION_ID
  resource_group: null   # Set via environment variable AZURE_RESOURCE_GROUP
  workspace_name: drpets-workspace
  region: eastus
  
  # Compute cluster specifications
  compute_name: gpu-cluster
  vm_size: Standard_NC6s_v3  # NVIDIA V100 GPU, 6 cores, 112 GB memory
  # Alternatives: Standard_NC12s_v3 (2x V100 GPUs), Standard_NC24s_v3 (4x V100 GPUs)
  min_nodes: 0  # Scale to 0 when not in use to save costs
  max_nodes: 2  # Scale up to 2 nodes (reduced from 4 due to higher GPU power)
  idle_seconds_before_scaledown: 600  # Scale down after 10 minutes of inactivity
  
  # Storage settings
  datastore_name: drpets_datastore
  
  # Budget constraints
  budget_limit_usd: 100.0  # Maximum budget in USD (increased for V100 pricing)
  auto_terminate: true    # Automatically terminate when training completes

# Experiment configuration
experiment:
  name: dr-pets-training
  description: DR-PETS training with GPU acceleration
  
  # Model parameters
  state_dim: 4
  action_dim: 2
  ensemble_size: 5
  epsilon: 0.05
  
  # Training parameters
  episodes: 100
  horizon: 25
  num_samples: 2000  # Increased due to V100's higher throughput
  num_particles: 32  # Increased for better parallelization on V100
  device: cuda  # Use GPU for training
  
  # Checkpointing
  checkpointing:
    enabled: true
    frequency: 10  # Save checkpoint every 10 episodes
    path: ./checkpoints
    
  # Data collection
  collect_data: true
  dataset_size: 10000
  
  # Hyperparameter optimization (optional)
  hyperparameter_tuning:
    enabled: false
    parameters:
      epsilon:
        distribution: uniform
        min_value: 0.01
        max_value: 0.1
      ensemble_size:
        values: [3, 5, 7]
  
  # Environment
  env:
    name: CartPole-v1
    seed: 42
  
  # Logging and monitoring
  tensorboard:
    enabled: true
    update_frequency: 1  # Update TensorBoard every episode
  
  mlflow:
    enabled: true
    tracking_uri: null  # Use the default Azure ML tracking

  # Performance monitoring
  profiling:
    enabled: true
    start_step: 0
    num_steps: 100
    
  # V100 specific optimizations  
  v100_optimizations:
    enabled: true
    mixed_precision: true  # Use FP16 for better performance
    cudnn_benchmark: true  # Optimize CUDA operations
    batch_size_multiplier: 2.0  # Larger batches for V100's capacity
    
  # Early stopping
  early_stopping:
    enabled: true
    metric_name: reward
    goal: maximize
    patience: 20

