experiment:
  ensemble_size: 5
  lambda_penalty: 0.5
  state_dim: 4
  action_dim: 2
  batch_size: 256
  density_model_path: "flow_density.pt"
  state_action_dataset: "state_action_dataset.pt"
  num_epochs: 50
  log_to_tensorboard: true
  log_dir: "runs/drpets"
  planner_log_to_tensorboard: true
  planner_log_dir: "runs/planner"
