experiment:
  state_dim: 4
  action_dim: 2
  ensemble_size: 5
  density_dataset_path: state_action_dataset.pt
  density_model_path: checkpoints/density_model.pt
  lambda_penalty: 0.01  # DR-PETS penalty strength
